import pandas as pd

# Load the dataset
df = pd.read_csv("tn_realistic_plastic_waste_2018_2024.csv")

# View first few records
df.head()
import matplotlib.pyplot as plt

# Group by district and sum the total waste
district_waste = df.groupby("District")["Total_Waste_Tons"].sum().sort_values(ascending=False)

# Plot
plt.figure(figsize=(14, 6))
district_waste.plot(kind="bar", color="seagreen")
plt.title("Total Plastic Waste Generated by District (2018–2024)", fontsize=14)
plt.ylabel("Total Waste (Tons)")
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Filter Chennai's data
chennai_df = df[df["District"] == "Chennai"]

# Plot the trend
plt.figure(figsize=(12, 5))
plt.plot(chennai_df["Month"], chennai_df["Total_Waste_Tons"], marker='o', linestyle='-', color='darkblue')
plt.title("Monthly Plastic Waste Trend – Chennai (2018–2024)", fontsize=14)
plt.xlabel("Month")
plt.ylabel("Waste (Tons)")
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()
